language: java
install: cp .travis.settings.xml $HOME/.m2/settings.xml
script: mvn package
deploy:
  provider: script
  script: mvn deploy
  on:
    tags: true
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email: false
cache:
  directories:
    - $HOME/.m2/repository/
