language: java
install:
script: if [ -z "$TRAVIS_TAG" ]; then mvn test; fi;
before_deploy: cp .travis.settings.xml $HOME/.m2/settings.xml
deploy:
  provider: script
  script: mvn deploy
  on:
    tags: true
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email: false
cache:
  directories:
    - $HOME/.m2/repository/
