language: java
install: echo 'No installation required'
script: if [ -z "$TRAVIS_TAG" ]; then mvn test; fi;
after_success:
  - if [ -z "$TRAVIS_TAG" ]; then bash <(curl -s https://codecov.io/bash); fi;
before_deploy: cp .travis.settings.xml $HOME/.m2/settings.xml
deploy:
  provider: script
  script: mvn deploy
  on:
    tags: true
after_deploy:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email: false
cache:
  directories:
    - $HOME/.m2/repository/
